Eliminate compiler warning - preferences.cc
error: both sides of operator are equivalent
[misc-redundant-expression,-warnings-as-errors]
is issued because PREF_PAD_INDENT = PREF_PAD_SPACE

Create a workaround.