Upgrade development computer to 2410
Upgrading a development computer to Ubuntu 2410 results in multiple
warnings from clang-tidy, mostly:
readability-math-missing-parentheses
readability-use-std-min-max

Most fixed using: clang-tidy --fix-errors
Others by hand.

Exception was:
src/exif.cc:1294:9: error: macro 'EXIF_DATA_AS_TEXT_MAX_COUNT' defines
an integral constant; prefer an enum instead
[modernize-macro-to-enum,-warnings-as-errors]

which auto-fixed to a single value enum.

This was changed to be a constexpr.