Creates a Python version of image-test.sh, which checks more conditions and minimizes runtime
This makes it easier to understand when the geeqie process did something
unexpected, and what that unexpected behavior might have been.  In particular,
it will now detect crashes on exit, which was not previously the case.

Note that, because the `xvfb-run` script doesn't pass signals to the command
that it started, if a `geeqie` process doesn't respond to the `--quit` remote
command, it may continue running indefinitely, even after the `Xvfb` server is
cleaned up appropriately.  See:
https://unix.stackexchange.com/questions/291804/howto-terminate-xvfb-run-properly

There are some signs that `meson` itself may detect this and kill the errant
`geeqie` processes, but this behavior is not documented at all.

This shows that the script forwards the geeqie return code, and identifies that the error occurred during shutdown:

```
$…/scripts/isolate-test.sh …/scripts/image-test.py …/build/src/geeqie …/build/test-images.p/images/RAW_CANON_350D.CR2
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
glx: failed to create drisw screen
failed to load driver: zink

(geeqie:3242332): dbind-WARNING **: 02:53:26.385: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Creating Geeqie dir:/tmp/tmp.zAdZOxrnDs/.config/geeqie

Creating Geeqie dir:/tmp/tmp.zAdZOxrnDs/.local/share/geeqie/collections

Creating Geeqie dir:/tmp/tmp.zAdZOxrnDs/.cache/geeqie/thumbnails

Creating Geeqie dir:/tmp/tmp.zAdZOxrnDs/.local/share/geeqie/metadata

Creating Geeqie dir:/tmp/tmp.zAdZOxrnDs/.config/geeqie/layouts

Warning: Directory Canon has an unexpected next pointer; ignored.
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
glx: failed to create drisw screen
failed to load driver: zink

(geeqie:3242382): dbind-WARNING **: 02:53:30.600: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Stack trace (most recent call last):
       1558: 	gdk_threads_leave();
       1559:
      >1560: 	*((int *)nullptr) = 13;
       1561: 	return 0;
       1562: }
       1563: /* vim: set shiftwidth=8 softtabstop=0 cindent cinoptions={1s: */
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault
Traceback (most recent call last):
  File "…/scripts/image-test.py", line 155, in <module>
    exit(main(sys.argv))
         ^^^^^^^^^^^^^^
  File "…/scripts/image-test.py", line 122, in main
    raise GeeqieTestError("shutdown", geeqie_proc)
GeeqieTestError: geeqie crashed during: shutdown

$ echo $?
139
```

And here's how this shows up in the aggregated `meson` output:
```
$meson test -C build
ninja: no work to do.
ninja: Entering directory `…/build'
ninja: no work to do.
   1/1144 geeqie:functional / Basic test                                                           OK               0.37s
   2/1144 geeqie:functional+image / Image_ DSCF0253.MPO                                            FAIL             5.69s   (exit status 139 or signal 11 SIGSEGV)
>>> MALLOC_PERTURB_=227 …/scripts/isolate-test.sh …/scripts/image-test.py …/build/src/geeqie …/build/test-images.p/images/DSCF0253.MPO

   3/1144 geeqie:functional+image / Image_ RAW_APTUS_75.MOS                                        FAIL             5.73s   (exit status 139 or signal 11 SIGSEGV)
>>> MALLOC_PERTURB_=76 …/scripts/isolate-test.sh …/scripts/image-test.py …/build/src/geeqie …/build/test-images.p/images/RAW_APTUS_75.MOS

   4/1144 geeqie:functional+image / Image_ Chimera-AV1-8bit-768x432-1160kbps-162.avif              FAIL             5.82s   (exit status 139 or signal 11 SIGSEGV)
>>> MALLOC_PERTURB_=189 …/scripts/isolate-test.sh …/scripts/image-test.py …/build/src/geeqie …/build/test-images.p/images/Chimera-AV1-8bit-768x432-1160kbps-162.avif
…
```